{% set name = "xyzpy" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xyzpy-{{ version }}.tar.gz
  sha256: 4f38442994da28f53a3dc6510750bbf793def5ad085f4f51804473490de080c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - dask-core >=0.11.1
    - h5netcdf >=0.2.2
    - h5py >=2.6.0
    - joblib >=0.12
    - numpy >=1.10.0
    - pandas >=0.20
    - python >=3.5
    - tqdm >=4.7.6
    - xarray >=0.9.0
    - matplotlib-base >=2.2.0

test:
  imports:
    - xyzpy
    - xyzpy.gen
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://xyzpy.readthedocs.io
  summary: Easily generate large parameter space data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcmgray
