{% set name = "xyzpy" %}
{% set version = "1.3.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/xyzpy-{{ version }}.tar.gz
  sha256: 4ba0aa08af546a8cdb66cc5bb96dea010ca0e2d36b5d8338e30d6e4f44201b89

build:
  entry_points:
    - xyzpy-grow = xyzpy_grow:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - dask-core
    - h5netcdf
    - h5py
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - tqdm
    - xarray

test:
  imports:
    - xyzpy
  commands:
    - pip check
    - xyzpy-grow --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/xyzpy/
  summary: Easily generate large parameter space data
  doc_url: https://xyzpy.readthedocs.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcmgray
